name: Sync PDFs from Google Drive to GitHub

on:
  workflow_dispatch: # Run manually only

jobs:
  sync_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run Sync Script
        env:
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python main/drive_to_github.py

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/rakzeh/pdf-automation.git
          git pull origin main --rebase  # Prevent merge conflicts
          git add pdfs/
          git commit -m "📄 Synced new PDFs from Google Drive" || echo "No changes to commit"
          git push origin main
