name: Sync PDFs from Google Drive to GitHub

on:
  workflow_dispatch: # Run manually only

jobs:
  sync_pdfs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git autotools-dev automake libtool libleptonica-dev liblept5 poppler-utils tesseract-ocr tesseract-ocr-eng tesseract-ocr-hin ghostscript qpdf pngquant unpaper libjbig2dec0 libffi-dev libssl-dev python3-dev ocrmypdf
          git clone https://github.com/agl/jbig2enc.git
          cd jbig2enc
          autoreconf -ivf
          ./configure && make
          sudo make install

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Sync Script
        env:
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: bash run.sh

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull origin main --rebase  # Prevent merge conflicts
          git add main/pdfs/
          git commit -m "📄 Synced new PDFs from Google Drive" || echo "No changes to commit"
          git push

      - name: 🔥 Delete Synced Files from Repository
        run: |
          git rm -r main/pdfs/ || echo "No files to delete"
          echo "🗑️ Removed main/pdfs/ after syncing"

      - name: Commit and Push Cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git stash  # Stash any unstaged changes
          git pull origin main --rebase  # Now pull without conflict
          git stash pop || echo "No stashed changes to apply"
          git commit -m "🧹 Removed PDFs and converted images after syncing" || echo "No changes to commit"
          git push
